export const data = [
  {
    id: 12409,
    name: "Adan Joe",
    schoolLevel: "Preparatoria - SEAD",
    subject: "Egnlish",
    grade: "6",
    topic: "Verb to be",
    date: new Date("11-17-2024").toLocaleDateString(),
    startClass: "10:00",
    endClass: "12:00",
    state: "done",
  },
  {
    id: 54643,
    name: "Jazmin Joe",
    schoolLevel: "Preparatoria - SEAD",
    subject: "Egnlish",
    grade: "6",
    topic: "Verb to be",
    date: new Date("11-17-2024").toLocaleDateString(),
    startClass: "10:00",
    endClass: "12:00",
    state: "done",
  },
  {
    id: 43399,
    name: "Adrian Joe",
    schoolLevel: "Preparatoria - SEAD",
    subject: "Math",
    grade: "6",
    topic: "Gemonetric",
    date: new Date("11-17-2024").toLocaleDateString(),
    startClass: "11:00",
    endClass: "12:00",
    state: "done",
  },
  {
    id: 87890,
    name: "Alab Maks",
    schoolLevel: "Universidad",
    subject: "Math",
    grade: "6",
    topic: "Gemonetric",
    date: new Date("15-17-2024").toLocaleDateString(),
    startClass: "11:00",
    endClass: "12:00",
    state: "done",
  },
  {
    id: 65800,
    name: "Max Youal",
    schoolLevel: "Preparatoria - SEAD",
    subject: "Math",
    grade: "6",
    topic: "Gemonetric",
    date: new Date("11-17-2024").toLocaleDateString(),
    startClass: "11:00",
    endClass: "12:00",
    state: "done",
  },
];
